# POST http://localhost:8000/addAssignment/
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3MjIwNzIwLCJpYXQiOjE3NDcyMTcxMjAsImp0aSI6IjA0ZmU1Nzc5OGZmNTRlZjBhYjEyMTlhY2NhMTZmYjZiIiwiaWQiOjYsInJvbGUiOiJ0ZWFjaGVyIn0.ZvZEl4ORMLwPXSqy8Qc8x0CjNNzB6KOf-RPsTERG4QE

# {
#   "title": "Math Assignment 1",
#   "description": "Complete exercises 1-10 from chapter 3. Show all your work.",
#   "subject": "Computer Network",
#   "deadline": "2024-12-15T23:59:00Z"
# }

# POST http://localhost:8000/login/
# {
#   "email": "sijal@gmail.com",
#   "password": "password321@" 
# }
GET http://localhost:8000/getAssignment/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3MzEwOTk5LCJpYXQiOjE3NDczMDczOTksImp0aSI6ImMxYjllN2I0Y2FhODQ0ODNiNDJmZjhiNjA5Njg2MWZkIiwidXNlcl9pZCI6NiwiZW1haWwiOiJzaWphbEBnbWFpbC5jb20iLCJyb2xlIjoidGVhY2hlciJ9.UdjXb9kqxrypww2lrWTHF4U-h8YrA9h1w_whB-S5fpo
